# Build on official GovReady-Q image but add our first_run.py script
# that automates initialization of initial state.

# if FROM image is changed, also change atokit-update.sh
FROM govready/govready-q-nightly
COPY first_run.py .