# Build on official GovReady-Q image but add our first_run.py script
# that automates initialization of initial state.

# if FROM image is changed, also change atokit-up.sh
FROM govready/govready-q
COPY first_run.py .